# Generated by Django 3.2.25 on 2024-06-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='related_page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
