# Generated by Django 3.2.25 on 2024-06-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_related_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='related_page',
        ),
    ]
