# Generated by Django 3.2.25 on 2024-06-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('mode_of_contact', models.CharField(choices=[('email', 'E-mail'), ('phone', 'Phone')], default='email', max_length=50, verbose_name='Conatct by')),
                ('question_categories', models.CharField(choices=[('general_inquiry', 'General Inquiry'), ('order', 'Order'), ('delivery_and_availability', 'Delivery and Availability'), ('feedback_and_suggestions', 'Feedback and Suggesstions'), ('other', 'Other')], default='certification', max_length=50, verbose_name='How can we help you?')),
                ('message', models.TextField(max_length=3000)),
            ],
        ),
    ]
