# Generated by Django 3.2.25 on 2024-06-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='mode_of_contact',
            field=models.CharField(choices=[('email', 'E-mail'), ('phone', 'Phone')], default='email', max_length=50, verbose_name='Contact by'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=1, max_length=25, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=2, max_length=10, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='question_categories',
            field=models.CharField(choices=[('general_inquiry', 'General Inquiry'), ('order', 'Order'), ('delivery_and_availability', 'Delivery and Availability'), ('feedback_and_suggestions', 'Feedback and Suggesstions'), ('other', 'Other')], default='certification', max_length=50, verbose_name='How can we help you?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=3000, verbose_name=''),
        ),
    ]
