# Generated by Django 4.2.27 on 2026-01-19 18:37

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_remove_testimonial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
