# Generated by Django 3.2.25 on 2024-06-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240603_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('large', 'Large')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
