# Generated by Django 3.2.25 on 2024-06-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_large',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_small',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
